// flow-typed signature: e0e4931e943f7cb78dc9b3aab9f804b9
// flow-typed version: <<STUB>>/react-lottie_v1.2.3/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-lottie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-lottie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-lottie/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-lottie/dist/index' {
  declare module.exports: $Exports<'react-lottie/dist'>;
}
declare module 'react-lottie/dist/index.js' {
  declare module.exports: $Exports<'react-lottie/dist'>;
}
