// flow-typed signature: 5cd92c94ca01929bc2e07f203877814f
// flow-typed version: <<STUB>>/react-infinite-scroll-component_v5.1.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-infinite-scroll-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-infinite-scroll-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-infinite-scroll-component/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-infinite-scroll-component/dist' {
  declare module.exports: any;
}

declare module 'react-infinite-scroll-component/dist/index.umd' {
  declare module.exports: any;
}

declare module 'react-infinite-scroll-component/jest.config' {
  declare module.exports: any;
}

declare module 'react-infinite-scroll-component/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-infinite-scroll-component/dist/index.es.js' {
  declare module.exports: $Exports<
    'react-infinite-scroll-component/dist/index.es'
  >;
}
declare module 'react-infinite-scroll-component/dist/index' {
  declare module.exports: $Exports<'react-infinite-scroll-component/dist'>;
}
declare module 'react-infinite-scroll-component/dist/index.js' {
  declare module.exports: $Exports<'react-infinite-scroll-component/dist'>;
}
declare module 'react-infinite-scroll-component/dist/index.umd.js' {
  declare module.exports: $Exports<
    'react-infinite-scroll-component/dist/index.umd'
  >;
}
declare module 'react-infinite-scroll-component/jest.config.js' {
  declare module.exports: $Exports<
    'react-infinite-scroll-component/jest.config'
  >;
}
declare module 'react-infinite-scroll-component/rollup.config.js' {
  declare module.exports: $Exports<
    'react-infinite-scroll-component/rollup.config'
  >;
}
