// flow-typed signature: 56fddd2099f2ff8431fce6da107972db
// flow-typed version: <<STUB>>/react-select_v3.1.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-select/animated/dist/react-select.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select.cjs' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/animated/dist/react-select.esm' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select.cjs' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/async-creatable/dist/react-select.esm' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select.cjs' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/async/dist/react-select.esm' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select.cjs' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/base/dist/react-select.esm' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select.cjs' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/creatable/dist/react-select.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-30113876.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-4322c0ed.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-4f270825.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-503cf1e8.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/index-52626178.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/react-select.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-062d63ee.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-073d29ba.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-95fb2b5c.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-9fdb8cd0.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/Select-b0ada71d.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/dist/stateManager-04f734a2.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/stateManager-149692c5.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/stateManager-1f3302b2.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/stateManager-61815400.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/dist/stateManager-d41587a2.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/utils-03a02e63.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-select/dist/utils-06b0d5a4.browser.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/utils-2db2ca57.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-select/dist/utils-711604ed.esm' {
  declare module.exports: any;
}

declare module 'react-select/dist/utils-896a48cb.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-select/src/__tests__/Async.test' {
  declare module.exports: any;
}

declare module 'react-select/src/__tests__/AsyncCreatable.test' {
  declare module.exports: any;
}

declare module 'react-select/src/__tests__/constants' {
  declare module.exports: any;
}

declare module 'react-select/src/__tests__/Creatable.test' {
  declare module.exports: any;
}

declare module 'react-select/src/__tests__/Select.test' {
  declare module.exports: any;
}

declare module 'react-select/src/__tests__/StateManaged.test' {
  declare module.exports: any;
}

declare module 'react-select/src/accessibility' {
  declare module.exports: any;
}

declare module 'react-select/src/animated' {
  declare module.exports: any;
}

declare module 'react-select/src/animated/Input' {
  declare module.exports: any;
}

declare module 'react-select/src/animated/MultiValue' {
  declare module.exports: any;
}

declare module 'react-select/src/animated/Placeholder' {
  declare module.exports: any;
}

declare module 'react-select/src/animated/SingleValue' {
  declare module.exports: any;
}

declare module 'react-select/src/animated/transitions' {
  declare module.exports: any;
}

declare module 'react-select/src/animated/ValueContainer' {
  declare module.exports: any;
}

declare module 'react-select/src/Async' {
  declare module.exports: any;
}

declare module 'react-select/src/AsyncCreatable' {
  declare module.exports: any;
}

declare module 'react-select/src/builtins' {
  declare module.exports: any;
}

declare module 'react-select/src/components/containers' {
  declare module.exports: any;
}

declare module 'react-select/src/components/Control' {
  declare module.exports: any;
}

declare module 'react-select/src/components/Group' {
  declare module.exports: any;
}

declare module 'react-select/src/components' {
  declare module.exports: any;
}

declare module 'react-select/src/components/indicators' {
  declare module.exports: any;
}

declare module 'react-select/src/components/Input' {
  declare module.exports: any;
}

declare module 'react-select/src/components/Menu' {
  declare module.exports: any;
}

declare module 'react-select/src/components/MultiValue' {
  declare module.exports: any;
}

declare module 'react-select/src/components/Option' {
  declare module.exports: any;
}

declare module 'react-select/src/components/Placeholder' {
  declare module.exports: any;
}

declare module 'react-select/src/components/SingleValue' {
  declare module.exports: any;
}

declare module 'react-select/src/Creatable' {
  declare module.exports: any;
}

declare module 'react-select/src/diacritics' {
  declare module.exports: any;
}

declare module 'react-select/src/filters' {
  declare module.exports: any;
}

declare module 'react-select/src' {
  declare module.exports: any;
}

declare module 'react-select/src/internal/A11yText' {
  declare module.exports: any;
}

declare module 'react-select/src/internal/DummyInput' {
  declare module.exports: any;
}

declare module 'react-select/src/internal' {
  declare module.exports: any;
}

declare module 'react-select/src/internal/NodeResolver' {
  declare module.exports: any;
}

declare module 'react-select/src/internal/react-fast-compare' {
  declare module.exports: any;
}

declare module 'react-select/src/internal/ScrollBlock' {
  declare module.exports: any;
}

declare module 'react-select/src/internal/ScrollCaptor' {
  declare module.exports: any;
}

declare module 'react-select/src/internal/ScrollLock/constants' {
  declare module.exports: any;
}

declare module 'react-select/src/internal/ScrollLock' {
  declare module.exports: any;
}

declare module 'react-select/src/internal/ScrollLock/utils' {
  declare module.exports: any;
}

declare module 'react-select/src/NonceProvider' {
  declare module.exports: any;
}

declare module 'react-select/src/Select' {
  declare module.exports: any;
}

declare module 'react-select/src/stateManager' {
  declare module.exports: any;
}

declare module 'react-select/src/styles' {
  declare module.exports: any;
}

declare module 'react-select/src/theme' {
  declare module.exports: any;
}

declare module 'react-select/src/types' {
  declare module.exports: any;
}

declare module 'react-select/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-select/animated/dist/react-select.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select.browser.cjs'>;
}
declare module 'react-select/animated/dist/react-select.browser.esm.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select.browser.esm'>;
}
declare module 'react-select/animated/dist/react-select.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select.cjs.dev'>;
}
declare module 'react-select/animated/dist/react-select.cjs.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select.cjs'>;
}
declare module 'react-select/animated/dist/react-select.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select.cjs.prod'>;
}
declare module 'react-select/animated/dist/react-select.esm.js' {
  declare module.exports: $Exports<'react-select/animated/dist/react-select.esm'>;
}
declare module 'react-select/async-creatable/dist/react-select.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select.browser.cjs'>;
}
declare module 'react-select/async-creatable/dist/react-select.browser.esm.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select.browser.esm'>;
}
declare module 'react-select/async-creatable/dist/react-select.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select.cjs.dev'>;
}
declare module 'react-select/async-creatable/dist/react-select.cjs.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select.cjs'>;
}
declare module 'react-select/async-creatable/dist/react-select.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select.cjs.prod'>;
}
declare module 'react-select/async-creatable/dist/react-select.esm.js' {
  declare module.exports: $Exports<'react-select/async-creatable/dist/react-select.esm'>;
}
declare module 'react-select/async/dist/react-select.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select.browser.cjs'>;
}
declare module 'react-select/async/dist/react-select.browser.esm.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select.browser.esm'>;
}
declare module 'react-select/async/dist/react-select.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select.cjs.dev'>;
}
declare module 'react-select/async/dist/react-select.cjs.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select.cjs'>;
}
declare module 'react-select/async/dist/react-select.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select.cjs.prod'>;
}
declare module 'react-select/async/dist/react-select.esm.js' {
  declare module.exports: $Exports<'react-select/async/dist/react-select.esm'>;
}
declare module 'react-select/base/dist/react-select.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select.browser.cjs'>;
}
declare module 'react-select/base/dist/react-select.browser.esm.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select.browser.esm'>;
}
declare module 'react-select/base/dist/react-select.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select.cjs.dev'>;
}
declare module 'react-select/base/dist/react-select.cjs.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select.cjs'>;
}
declare module 'react-select/base/dist/react-select.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select.cjs.prod'>;
}
declare module 'react-select/base/dist/react-select.esm.js' {
  declare module.exports: $Exports<'react-select/base/dist/react-select.esm'>;
}
declare module 'react-select/creatable/dist/react-select.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select.browser.cjs'>;
}
declare module 'react-select/creatable/dist/react-select.browser.esm.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select.browser.esm'>;
}
declare module 'react-select/creatable/dist/react-select.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select.cjs.dev'>;
}
declare module 'react-select/creatable/dist/react-select.cjs.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select.cjs'>;
}
declare module 'react-select/creatable/dist/react-select.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select.cjs.prod'>;
}
declare module 'react-select/creatable/dist/react-select.esm.js' {
  declare module.exports: $Exports<'react-select/creatable/dist/react-select.esm'>;
}
declare module 'react-select/dist/index-30113876.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/dist/index-30113876.browser.cjs'>;
}
declare module 'react-select/dist/index-4322c0ed.browser.esm.js' {
  declare module.exports: $Exports<'react-select/dist/index-4322c0ed.browser.esm'>;
}
declare module 'react-select/dist/index-4f270825.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/index-4f270825.cjs.prod'>;
}
declare module 'react-select/dist/index-503cf1e8.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/index-503cf1e8.cjs.dev'>;
}
declare module 'react-select/dist/index-52626178.esm.js' {
  declare module.exports: $Exports<'react-select/dist/index-52626178.esm'>;
}
declare module 'react-select/dist/react-select.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.browser.cjs'>;
}
declare module 'react-select/dist/react-select.browser.esm.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.browser.esm'>;
}
declare module 'react-select/dist/react-select.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs.dev'>;
}
declare module 'react-select/dist/react-select.cjs.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs'>;
}
declare module 'react-select/dist/react-select.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.cjs.prod'>;
}
declare module 'react-select/dist/react-select.esm.js' {
  declare module.exports: $Exports<'react-select/dist/react-select.esm'>;
}
declare module 'react-select/dist/Select-062d63ee.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/Select-062d63ee.cjs.dev'>;
}
declare module 'react-select/dist/Select-073d29ba.esm.js' {
  declare module.exports: $Exports<'react-select/dist/Select-073d29ba.esm'>;
}
declare module 'react-select/dist/Select-95fb2b5c.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/Select-95fb2b5c.cjs.prod'>;
}
declare module 'react-select/dist/Select-9fdb8cd0.browser.esm.js' {
  declare module.exports: $Exports<'react-select/dist/Select-9fdb8cd0.browser.esm'>;
}
declare module 'react-select/dist/Select-b0ada71d.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/dist/Select-b0ada71d.browser.cjs'>;
}
declare module 'react-select/dist/stateManager-04f734a2.browser.esm.js' {
  declare module.exports: $Exports<'react-select/dist/stateManager-04f734a2.browser.esm'>;
}
declare module 'react-select/dist/stateManager-149692c5.esm.js' {
  declare module.exports: $Exports<'react-select/dist/stateManager-149692c5.esm'>;
}
declare module 'react-select/dist/stateManager-1f3302b2.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/stateManager-1f3302b2.cjs.prod'>;
}
declare module 'react-select/dist/stateManager-61815400.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/dist/stateManager-61815400.browser.cjs'>;
}
declare module 'react-select/dist/stateManager-d41587a2.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/stateManager-d41587a2.cjs.dev'>;
}
declare module 'react-select/dist/utils-03a02e63.cjs.dev.js' {
  declare module.exports: $Exports<'react-select/dist/utils-03a02e63.cjs.dev'>;
}
declare module 'react-select/dist/utils-06b0d5a4.browser.esm.js' {
  declare module.exports: $Exports<'react-select/dist/utils-06b0d5a4.browser.esm'>;
}
declare module 'react-select/dist/utils-2db2ca57.cjs.prod.js' {
  declare module.exports: $Exports<'react-select/dist/utils-2db2ca57.cjs.prod'>;
}
declare module 'react-select/dist/utils-711604ed.esm.js' {
  declare module.exports: $Exports<'react-select/dist/utils-711604ed.esm'>;
}
declare module 'react-select/dist/utils-896a48cb.browser.cjs.js' {
  declare module.exports: $Exports<'react-select/dist/utils-896a48cb.browser.cjs'>;
}
declare module 'react-select/src/__tests__/Async.test.js' {
  declare module.exports: $Exports<'react-select/src/__tests__/Async.test'>;
}
declare module 'react-select/src/__tests__/AsyncCreatable.test.js' {
  declare module.exports: $Exports<'react-select/src/__tests__/AsyncCreatable.test'>;
}
declare module 'react-select/src/__tests__/constants.js' {
  declare module.exports: $Exports<'react-select/src/__tests__/constants'>;
}
declare module 'react-select/src/__tests__/Creatable.test.js' {
  declare module.exports: $Exports<'react-select/src/__tests__/Creatable.test'>;
}
declare module 'react-select/src/__tests__/Select.test.js' {
  declare module.exports: $Exports<'react-select/src/__tests__/Select.test'>;
}
declare module 'react-select/src/__tests__/StateManaged.test.js' {
  declare module.exports: $Exports<'react-select/src/__tests__/StateManaged.test'>;
}
declare module 'react-select/src/accessibility/index' {
  declare module.exports: $Exports<'react-select/src/accessibility'>;
}
declare module 'react-select/src/accessibility/index.js' {
  declare module.exports: $Exports<'react-select/src/accessibility'>;
}
declare module 'react-select/src/animated/index' {
  declare module.exports: $Exports<'react-select/src/animated'>;
}
declare module 'react-select/src/animated/index.js' {
  declare module.exports: $Exports<'react-select/src/animated'>;
}
declare module 'react-select/src/animated/Input.js' {
  declare module.exports: $Exports<'react-select/src/animated/Input'>;
}
declare module 'react-select/src/animated/MultiValue.js' {
  declare module.exports: $Exports<'react-select/src/animated/MultiValue'>;
}
declare module 'react-select/src/animated/Placeholder.js' {
  declare module.exports: $Exports<'react-select/src/animated/Placeholder'>;
}
declare module 'react-select/src/animated/SingleValue.js' {
  declare module.exports: $Exports<'react-select/src/animated/SingleValue'>;
}
declare module 'react-select/src/animated/transitions.js' {
  declare module.exports: $Exports<'react-select/src/animated/transitions'>;
}
declare module 'react-select/src/animated/ValueContainer.js' {
  declare module.exports: $Exports<'react-select/src/animated/ValueContainer'>;
}
declare module 'react-select/src/Async.js' {
  declare module.exports: $Exports<'react-select/src/Async'>;
}
declare module 'react-select/src/AsyncCreatable.js' {
  declare module.exports: $Exports<'react-select/src/AsyncCreatable'>;
}
declare module 'react-select/src/builtins.js' {
  declare module.exports: $Exports<'react-select/src/builtins'>;
}
declare module 'react-select/src/components/containers.js' {
  declare module.exports: $Exports<'react-select/src/components/containers'>;
}
declare module 'react-select/src/components/Control.js' {
  declare module.exports: $Exports<'react-select/src/components/Control'>;
}
declare module 'react-select/src/components/Group.js' {
  declare module.exports: $Exports<'react-select/src/components/Group'>;
}
declare module 'react-select/src/components/index' {
  declare module.exports: $Exports<'react-select/src/components'>;
}
declare module 'react-select/src/components/index.js' {
  declare module.exports: $Exports<'react-select/src/components'>;
}
declare module 'react-select/src/components/indicators.js' {
  declare module.exports: $Exports<'react-select/src/components/indicators'>;
}
declare module 'react-select/src/components/Input.js' {
  declare module.exports: $Exports<'react-select/src/components/Input'>;
}
declare module 'react-select/src/components/Menu.js' {
  declare module.exports: $Exports<'react-select/src/components/Menu'>;
}
declare module 'react-select/src/components/MultiValue.js' {
  declare module.exports: $Exports<'react-select/src/components/MultiValue'>;
}
declare module 'react-select/src/components/Option.js' {
  declare module.exports: $Exports<'react-select/src/components/Option'>;
}
declare module 'react-select/src/components/Placeholder.js' {
  declare module.exports: $Exports<'react-select/src/components/Placeholder'>;
}
declare module 'react-select/src/components/SingleValue.js' {
  declare module.exports: $Exports<'react-select/src/components/SingleValue'>;
}
declare module 'react-select/src/Creatable.js' {
  declare module.exports: $Exports<'react-select/src/Creatable'>;
}
declare module 'react-select/src/diacritics.js' {
  declare module.exports: $Exports<'react-select/src/diacritics'>;
}
declare module 'react-select/src/filters.js' {
  declare module.exports: $Exports<'react-select/src/filters'>;
}
declare module 'react-select/src/index' {
  declare module.exports: $Exports<'react-select/src'>;
}
declare module 'react-select/src/index.js' {
  declare module.exports: $Exports<'react-select/src'>;
}
declare module 'react-select/src/internal/A11yText.js' {
  declare module.exports: $Exports<'react-select/src/internal/A11yText'>;
}
declare module 'react-select/src/internal/DummyInput.js' {
  declare module.exports: $Exports<'react-select/src/internal/DummyInput'>;
}
declare module 'react-select/src/internal/index' {
  declare module.exports: $Exports<'react-select/src/internal'>;
}
declare module 'react-select/src/internal/index.js' {
  declare module.exports: $Exports<'react-select/src/internal'>;
}
declare module 'react-select/src/internal/NodeResolver.js' {
  declare module.exports: $Exports<'react-select/src/internal/NodeResolver'>;
}
declare module 'react-select/src/internal/react-fast-compare.js' {
  declare module.exports: $Exports<'react-select/src/internal/react-fast-compare'>;
}
declare module 'react-select/src/internal/ScrollBlock.js' {
  declare module.exports: $Exports<'react-select/src/internal/ScrollBlock'>;
}
declare module 'react-select/src/internal/ScrollCaptor.js' {
  declare module.exports: $Exports<'react-select/src/internal/ScrollCaptor'>;
}
declare module 'react-select/src/internal/ScrollLock/constants.js' {
  declare module.exports: $Exports<'react-select/src/internal/ScrollLock/constants'>;
}
declare module 'react-select/src/internal/ScrollLock/index' {
  declare module.exports: $Exports<'react-select/src/internal/ScrollLock'>;
}
declare module 'react-select/src/internal/ScrollLock/index.js' {
  declare module.exports: $Exports<'react-select/src/internal/ScrollLock'>;
}
declare module 'react-select/src/internal/ScrollLock/utils.js' {
  declare module.exports: $Exports<'react-select/src/internal/ScrollLock/utils'>;
}
declare module 'react-select/src/NonceProvider.js' {
  declare module.exports: $Exports<'react-select/src/NonceProvider'>;
}
declare module 'react-select/src/Select.js' {
  declare module.exports: $Exports<'react-select/src/Select'>;
}
declare module 'react-select/src/stateManager.js' {
  declare module.exports: $Exports<'react-select/src/stateManager'>;
}
declare module 'react-select/src/styles.js' {
  declare module.exports: $Exports<'react-select/src/styles'>;
}
declare module 'react-select/src/theme.js' {
  declare module.exports: $Exports<'react-select/src/theme'>;
}
declare module 'react-select/src/types.js' {
  declare module.exports: $Exports<'react-select/src/types'>;
}
declare module 'react-select/src/utils.js' {
  declare module.exports: $Exports<'react-select/src/utils'>;
}
