// flow-typed signature: 8e010faa52ba5dd650ba6fcf3ccdbaa2
// flow-typed version: <<STUB>>/svg-inline-react_vv3.2.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-inline-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-inline-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-inline-react/dist' {
  declare module.exports: any;
}

declare module 'svg-inline-react/gulpfile' {
  declare module.exports: any;
}

declare module 'svg-inline-react/karma.conf' {
  declare module.exports: any;
}

declare module 'svg-inline-react/lib' {
  declare module.exports: any;
}

declare module 'svg-inline-react/lib/util' {
  declare module.exports: any;
}

declare module 'svg-inline-react/src' {
  declare module.exports: any;
}

declare module 'svg-inline-react/src/util' {
  declare module.exports: any;
}

declare module 'svg-inline-react/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-inline-react/dist/index' {
  declare module.exports: $Exports<'svg-inline-react/dist'>;
}
declare module 'svg-inline-react/dist/index.js' {
  declare module.exports: $Exports<'svg-inline-react/dist'>;
}
declare module 'svg-inline-react/gulpfile.js' {
  declare module.exports: $Exports<'svg-inline-react/gulpfile'>;
}
declare module 'svg-inline-react/karma.conf.js' {
  declare module.exports: $Exports<'svg-inline-react/karma.conf'>;
}
declare module 'svg-inline-react/lib/index' {
  declare module.exports: $Exports<'svg-inline-react/lib'>;
}
declare module 'svg-inline-react/lib/index.js' {
  declare module.exports: $Exports<'svg-inline-react/lib'>;
}
declare module 'svg-inline-react/lib/util.js' {
  declare module.exports: $Exports<'svg-inline-react/lib/util'>;
}
declare module 'svg-inline-react/src/index' {
  declare module.exports: $Exports<'svg-inline-react/src'>;
}
declare module 'svg-inline-react/src/index.js' {
  declare module.exports: $Exports<'svg-inline-react/src'>;
}
declare module 'svg-inline-react/src/util.js' {
  declare module.exports: $Exports<'svg-inline-react/src/util'>;
}
declare module 'svg-inline-react/webpack.config.js' {
  declare module.exports: $Exports<'svg-inline-react/webpack.config'>;
}
