// flow-typed signature: 39dd8e66e76bae6651a5e881a63e2141
// flow-typed version: <<STUB>>/swiper_v6.1.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swiper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swiper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swiper/cjs/components/a11y/a11y' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/autoplay/autoplay' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/controller/controller' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/breakpoints/getBreakpoint' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/breakpoints' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/breakpoints/setBreakpoint' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/check-overflow' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/classes/addClasses' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/classes' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/classes/removeClasses' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/core-class' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/defaults' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/events-emitter' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/events' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/events/onClick' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/events/onResize' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/events/onScroll' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/events/onTouchEnd' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/events/onTouchMove' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/events/onTouchStart' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/grab-cursor' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/grab-cursor/setGrabCursor' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/grab-cursor/unsetGrabCursor' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/images' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/images/loadImage' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/images/preloadImages' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/loop' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/loop/loopCreate' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/loop/loopDestroy' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/loop/loopFix' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/manipulation/addSlide' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/manipulation/appendSlide' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/manipulation' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/manipulation/prependSlide' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/manipulation/removeAllSlides' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/manipulation/removeSlide' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/modular' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/slide' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/slide/slideNext' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/slide/slidePrev' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/slide/slideReset' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/slide/slideTo' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/slide/slideToClickedSlide' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/slide/slideToClosest' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/slide/slideToLoop' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/transition' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/transition/setTransition' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/transition/transitionEnd' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/transition/transitionStart' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/translate/getTranslate' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/translate' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/translate/maxTranslate' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/translate/minTranslate' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/translate/setTranslate' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/translate/translateTo' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update/updateActiveIndex' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update/updateAutoHeight' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update/updateClickedSlide' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update/updateProgress' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update/updateSize' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update/updateSlides' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update/updateSlidesClasses' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update/updateSlidesOffset' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/core/update/updateSlidesProgress' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/effect-coverflow/effect-coverflow' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/effect-cube/effect-cube' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/effect-fade/effect-fade' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/effect-flip/effect-flip' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/hash-navigation/hash-navigation' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/history/history' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/keyboard/keyboard' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/lazy/lazy' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/mousewheel/mousewheel' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/navigation/navigation' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/pagination/pagination' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/parallax/parallax' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/scrollbar/scrollbar' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/thumbs/thumbs' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/virtual/virtual' {
  declare module.exports: any;
}

declare module 'swiper/cjs/components/zoom/zoom' {
  declare module.exports: any;
}

declare module 'swiper/cjs/modules/observer/observer' {
  declare module.exports: any;
}

declare module 'swiper/cjs/modules/resize/resize' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/get-changed-params' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/get-children' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/get-params' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/init-swiper' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/loop' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/params-list' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/swiper-slide' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/swiper' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/update-swiper' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/use-isomorphic-layout-effect' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/utils' {
  declare module.exports: any;
}

declare module 'swiper/cjs/react/virtual' {
  declare module.exports: any;
}

declare module 'swiper/cjs/utils/dom' {
  declare module.exports: any;
}

declare module 'swiper/cjs/utils/get-browser' {
  declare module.exports: any;
}

declare module 'swiper/cjs/utils/get-device' {
  declare module.exports: any;
}

declare module 'swiper/cjs/utils/get-support' {
  declare module.exports: any;
}

declare module 'swiper/cjs/utils/utils' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/a11y/a11y' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/autoplay/autoplay' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/controller/controller' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/breakpoints/getBreakpoint' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/breakpoints' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/breakpoints/setBreakpoint' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/check-overflow' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/classes/addClasses' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/classes' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/classes/removeClasses' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/core-class' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/defaults' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/events-emitter' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/events' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/events/onClick' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/events/onResize' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/events/onScroll' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/events/onTouchEnd' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/events/onTouchMove' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/events/onTouchStart' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/grab-cursor' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/grab-cursor/setGrabCursor' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/grab-cursor/unsetGrabCursor' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/images' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/images/loadImage' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/images/preloadImages' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/loop' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/loop/loopCreate' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/loop/loopDestroy' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/loop/loopFix' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/manipulation/addSlide' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/manipulation/appendSlide' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/manipulation' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/manipulation/prependSlide' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/manipulation/removeAllSlides' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/manipulation/removeSlide' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/modular' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/slide' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/slide/slideNext' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/slide/slidePrev' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/slide/slideReset' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/slide/slideTo' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/slide/slideToClickedSlide' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/slide/slideToClosest' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/slide/slideToLoop' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/transition' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/transition/setTransition' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/transition/transitionEnd' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/transition/transitionStart' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/translate/getTranslate' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/translate' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/translate/maxTranslate' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/translate/minTranslate' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/translate/setTranslate' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/translate/translateTo' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update/updateActiveIndex' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update/updateAutoHeight' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update/updateClickedSlide' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update/updateProgress' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update/updateSize' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update/updateSlides' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update/updateSlidesClasses' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update/updateSlidesOffset' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/core/update/updateSlidesProgress' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/effect-coverflow/effect-coverflow' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/effect-cube/effect-cube' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/effect-fade/effect-fade' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/effect-flip/effect-flip' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/hash-navigation/hash-navigation' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/history/history' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/keyboard/keyboard' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/lazy/lazy' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/mousewheel/mousewheel' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/navigation/navigation' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/pagination/pagination' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/parallax/parallax' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/scrollbar/scrollbar' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/thumbs/thumbs' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/virtual/virtual' {
  declare module.exports: any;
}

declare module 'swiper/esm/components/zoom/zoom' {
  declare module.exports: any;
}

declare module 'swiper/esm/modules/observer/observer' {
  declare module.exports: any;
}

declare module 'swiper/esm/modules/resize/resize' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/get-changed-params' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/get-children' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/get-params' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/init-swiper' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/loop' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/params-list' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/swiper-slide' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/swiper' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/update-swiper' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/use-isomorphic-layout-effect' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/utils' {
  declare module.exports: any;
}

declare module 'swiper/esm/react/virtual' {
  declare module.exports: any;
}

declare module 'swiper/esm/utils/dom' {
  declare module.exports: any;
}

declare module 'swiper/esm/utils/get-browser' {
  declare module.exports: any;
}

declare module 'swiper/esm/utils/get-device' {
  declare module.exports: any;
}

declare module 'swiper/esm/utils/get-support' {
  declare module.exports: any;
}

declare module 'swiper/esm/utils/utils' {
  declare module.exports: any;
}

declare module 'swiper/swiper-bundle.cjs' {
  declare module.exports: any;
}

declare module 'swiper/swiper-bundle.esm.browser' {
  declare module.exports: any;
}

declare module 'swiper/swiper-bundle.esm.browser.min' {
  declare module.exports: any;
}

declare module 'swiper/swiper-bundle.esm' {
  declare module.exports: any;
}

declare module 'swiper/swiper-bundle' {
  declare module.exports: any;
}

declare module 'swiper/swiper-bundle.min' {
  declare module.exports: any;
}

declare module 'swiper/swiper-react.cjs' {
  declare module.exports: any;
}

declare module 'swiper/swiper-react.esm' {
  declare module.exports: any;
}

declare module 'swiper/swiper.cjs' {
  declare module.exports: any;
}

declare module 'swiper/swiper.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swiper/cjs/components/a11y/a11y.js' {
  declare module.exports: $Exports<'swiper/cjs/components/a11y/a11y'>;
}
declare module 'swiper/cjs/components/autoplay/autoplay.js' {
  declare module.exports: $Exports<'swiper/cjs/components/autoplay/autoplay'>;
}
declare module 'swiper/cjs/components/controller/controller.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/controller/controller'
  >;
}
declare module 'swiper/cjs/components/core/breakpoints/getBreakpoint.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/breakpoints/getBreakpoint'
  >;
}
declare module 'swiper/cjs/components/core/breakpoints/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/breakpoints'>;
}
declare module 'swiper/cjs/components/core/breakpoints/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/breakpoints'>;
}
declare module 'swiper/cjs/components/core/breakpoints/setBreakpoint.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/breakpoints/setBreakpoint'
  >;
}
declare module 'swiper/cjs/components/core/check-overflow/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/check-overflow'>;
}
declare module 'swiper/cjs/components/core/check-overflow/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/check-overflow'>;
}
declare module 'swiper/cjs/components/core/classes/addClasses.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/classes/addClasses'
  >;
}
declare module 'swiper/cjs/components/core/classes/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/classes'>;
}
declare module 'swiper/cjs/components/core/classes/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/classes'>;
}
declare module 'swiper/cjs/components/core/classes/removeClasses.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/classes/removeClasses'
  >;
}
declare module 'swiper/cjs/components/core/core-class.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/core-class'>;
}
declare module 'swiper/cjs/components/core/defaults.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/defaults'>;
}
declare module 'swiper/cjs/components/core/events-emitter.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/events-emitter'>;
}
declare module 'swiper/cjs/components/core/events/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/events'>;
}
declare module 'swiper/cjs/components/core/events/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/events'>;
}
declare module 'swiper/cjs/components/core/events/onClick.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/events/onClick'>;
}
declare module 'swiper/cjs/components/core/events/onResize.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/events/onResize'
  >;
}
declare module 'swiper/cjs/components/core/events/onScroll.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/events/onScroll'
  >;
}
declare module 'swiper/cjs/components/core/events/onTouchEnd.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/events/onTouchEnd'
  >;
}
declare module 'swiper/cjs/components/core/events/onTouchMove.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/events/onTouchMove'
  >;
}
declare module 'swiper/cjs/components/core/events/onTouchStart.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/events/onTouchStart'
  >;
}
declare module 'swiper/cjs/components/core/grab-cursor/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/grab-cursor'>;
}
declare module 'swiper/cjs/components/core/grab-cursor/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/grab-cursor'>;
}
declare module 'swiper/cjs/components/core/grab-cursor/setGrabCursor.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/grab-cursor/setGrabCursor'
  >;
}
declare module 'swiper/cjs/components/core/grab-cursor/unsetGrabCursor.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/grab-cursor/unsetGrabCursor'
  >;
}
declare module 'swiper/cjs/components/core/images/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/images'>;
}
declare module 'swiper/cjs/components/core/images/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/images'>;
}
declare module 'swiper/cjs/components/core/images/loadImage.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/images/loadImage'
  >;
}
declare module 'swiper/cjs/components/core/images/preloadImages.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/images/preloadImages'
  >;
}
declare module 'swiper/cjs/components/core/loop/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/loop'>;
}
declare module 'swiper/cjs/components/core/loop/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/loop'>;
}
declare module 'swiper/cjs/components/core/loop/loopCreate.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/loop/loopCreate'
  >;
}
declare module 'swiper/cjs/components/core/loop/loopDestroy.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/loop/loopDestroy'
  >;
}
declare module 'swiper/cjs/components/core/loop/loopFix.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/loop/loopFix'>;
}
declare module 'swiper/cjs/components/core/manipulation/addSlide.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/manipulation/addSlide'
  >;
}
declare module 'swiper/cjs/components/core/manipulation/appendSlide.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/manipulation/appendSlide'
  >;
}
declare module 'swiper/cjs/components/core/manipulation/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/manipulation'>;
}
declare module 'swiper/cjs/components/core/manipulation/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/manipulation'>;
}
declare module 'swiper/cjs/components/core/manipulation/prependSlide.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/manipulation/prependSlide'
  >;
}
declare module 'swiper/cjs/components/core/manipulation/removeAllSlides.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/manipulation/removeAllSlides'
  >;
}
declare module 'swiper/cjs/components/core/manipulation/removeSlide.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/manipulation/removeSlide'
  >;
}
declare module 'swiper/cjs/components/core/modular.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/modular'>;
}
declare module 'swiper/cjs/components/core/slide/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/slide'>;
}
declare module 'swiper/cjs/components/core/slide/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/slide'>;
}
declare module 'swiper/cjs/components/core/slide/slideNext.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/slide/slideNext'
  >;
}
declare module 'swiper/cjs/components/core/slide/slidePrev.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/slide/slidePrev'
  >;
}
declare module 'swiper/cjs/components/core/slide/slideReset.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/slide/slideReset'
  >;
}
declare module 'swiper/cjs/components/core/slide/slideTo.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/slide/slideTo'>;
}
declare module 'swiper/cjs/components/core/slide/slideToClickedSlide.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/slide/slideToClickedSlide'
  >;
}
declare module 'swiper/cjs/components/core/slide/slideToClosest.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/slide/slideToClosest'
  >;
}
declare module 'swiper/cjs/components/core/slide/slideToLoop.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/slide/slideToLoop'
  >;
}
declare module 'swiper/cjs/components/core/transition/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/transition'>;
}
declare module 'swiper/cjs/components/core/transition/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/transition'>;
}
declare module 'swiper/cjs/components/core/transition/setTransition.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/transition/setTransition'
  >;
}
declare module 'swiper/cjs/components/core/transition/transitionEnd.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/transition/transitionEnd'
  >;
}
declare module 'swiper/cjs/components/core/transition/transitionStart.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/transition/transitionStart'
  >;
}
declare module 'swiper/cjs/components/core/translate/getTranslate.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/translate/getTranslate'
  >;
}
declare module 'swiper/cjs/components/core/translate/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/translate'>;
}
declare module 'swiper/cjs/components/core/translate/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/translate'>;
}
declare module 'swiper/cjs/components/core/translate/maxTranslate.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/translate/maxTranslate'
  >;
}
declare module 'swiper/cjs/components/core/translate/minTranslate.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/translate/minTranslate'
  >;
}
declare module 'swiper/cjs/components/core/translate/setTranslate.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/translate/setTranslate'
  >;
}
declare module 'swiper/cjs/components/core/translate/translateTo.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/translate/translateTo'
  >;
}
declare module 'swiper/cjs/components/core/update/index' {
  declare module.exports: $Exports<'swiper/cjs/components/core/update'>;
}
declare module 'swiper/cjs/components/core/update/index.js' {
  declare module.exports: $Exports<'swiper/cjs/components/core/update'>;
}
declare module 'swiper/cjs/components/core/update/updateActiveIndex.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/update/updateActiveIndex'
  >;
}
declare module 'swiper/cjs/components/core/update/updateAutoHeight.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/update/updateAutoHeight'
  >;
}
declare module 'swiper/cjs/components/core/update/updateClickedSlide.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/update/updateClickedSlide'
  >;
}
declare module 'swiper/cjs/components/core/update/updateProgress.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/update/updateProgress'
  >;
}
declare module 'swiper/cjs/components/core/update/updateSize.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/update/updateSize'
  >;
}
declare module 'swiper/cjs/components/core/update/updateSlides.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/update/updateSlides'
  >;
}
declare module 'swiper/cjs/components/core/update/updateSlidesClasses.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/update/updateSlidesClasses'
  >;
}
declare module 'swiper/cjs/components/core/update/updateSlidesOffset.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/update/updateSlidesOffset'
  >;
}
declare module 'swiper/cjs/components/core/update/updateSlidesProgress.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/core/update/updateSlidesProgress'
  >;
}
declare module 'swiper/cjs/components/effect-coverflow/effect-coverflow.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/effect-coverflow/effect-coverflow'
  >;
}
declare module 'swiper/cjs/components/effect-cube/effect-cube.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/effect-cube/effect-cube'
  >;
}
declare module 'swiper/cjs/components/effect-fade/effect-fade.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/effect-fade/effect-fade'
  >;
}
declare module 'swiper/cjs/components/effect-flip/effect-flip.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/effect-flip/effect-flip'
  >;
}
declare module 'swiper/cjs/components/hash-navigation/hash-navigation.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/hash-navigation/hash-navigation'
  >;
}
declare module 'swiper/cjs/components/history/history.js' {
  declare module.exports: $Exports<'swiper/cjs/components/history/history'>;
}
declare module 'swiper/cjs/components/keyboard/keyboard.js' {
  declare module.exports: $Exports<'swiper/cjs/components/keyboard/keyboard'>;
}
declare module 'swiper/cjs/components/lazy/lazy.js' {
  declare module.exports: $Exports<'swiper/cjs/components/lazy/lazy'>;
}
declare module 'swiper/cjs/components/mousewheel/mousewheel.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/mousewheel/mousewheel'
  >;
}
declare module 'swiper/cjs/components/navigation/navigation.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/navigation/navigation'
  >;
}
declare module 'swiper/cjs/components/pagination/pagination.js' {
  declare module.exports: $Exports<
    'swiper/cjs/components/pagination/pagination'
  >;
}
declare module 'swiper/cjs/components/parallax/parallax.js' {
  declare module.exports: $Exports<'swiper/cjs/components/parallax/parallax'>;
}
declare module 'swiper/cjs/components/scrollbar/scrollbar.js' {
  declare module.exports: $Exports<'swiper/cjs/components/scrollbar/scrollbar'>;
}
declare module 'swiper/cjs/components/thumbs/thumbs.js' {
  declare module.exports: $Exports<'swiper/cjs/components/thumbs/thumbs'>;
}
declare module 'swiper/cjs/components/virtual/virtual.js' {
  declare module.exports: $Exports<'swiper/cjs/components/virtual/virtual'>;
}
declare module 'swiper/cjs/components/zoom/zoom.js' {
  declare module.exports: $Exports<'swiper/cjs/components/zoom/zoom'>;
}
declare module 'swiper/cjs/modules/observer/observer.js' {
  declare module.exports: $Exports<'swiper/cjs/modules/observer/observer'>;
}
declare module 'swiper/cjs/modules/resize/resize.js' {
  declare module.exports: $Exports<'swiper/cjs/modules/resize/resize'>;
}
declare module 'swiper/cjs/react/get-changed-params.js' {
  declare module.exports: $Exports<'swiper/cjs/react/get-changed-params'>;
}
declare module 'swiper/cjs/react/get-children.js' {
  declare module.exports: $Exports<'swiper/cjs/react/get-children'>;
}
declare module 'swiper/cjs/react/get-params.js' {
  declare module.exports: $Exports<'swiper/cjs/react/get-params'>;
}
declare module 'swiper/cjs/react/init-swiper.js' {
  declare module.exports: $Exports<'swiper/cjs/react/init-swiper'>;
}
declare module 'swiper/cjs/react/loop.js' {
  declare module.exports: $Exports<'swiper/cjs/react/loop'>;
}
declare module 'swiper/cjs/react/params-list.js' {
  declare module.exports: $Exports<'swiper/cjs/react/params-list'>;
}
declare module 'swiper/cjs/react/swiper-slide.js' {
  declare module.exports: $Exports<'swiper/cjs/react/swiper-slide'>;
}
declare module 'swiper/cjs/react/swiper.js' {
  declare module.exports: $Exports<'swiper/cjs/react/swiper'>;
}
declare module 'swiper/cjs/react/update-swiper.js' {
  declare module.exports: $Exports<'swiper/cjs/react/update-swiper'>;
}
declare module 'swiper/cjs/react/use-isomorphic-layout-effect.js' {
  declare module.exports: $Exports<
    'swiper/cjs/react/use-isomorphic-layout-effect'
  >;
}
declare module 'swiper/cjs/react/utils.js' {
  declare module.exports: $Exports<'swiper/cjs/react/utils'>;
}
declare module 'swiper/cjs/react/virtual.js' {
  declare module.exports: $Exports<'swiper/cjs/react/virtual'>;
}
declare module 'swiper/cjs/utils/dom.js' {
  declare module.exports: $Exports<'swiper/cjs/utils/dom'>;
}
declare module 'swiper/cjs/utils/get-browser.js' {
  declare module.exports: $Exports<'swiper/cjs/utils/get-browser'>;
}
declare module 'swiper/cjs/utils/get-device.js' {
  declare module.exports: $Exports<'swiper/cjs/utils/get-device'>;
}
declare module 'swiper/cjs/utils/get-support.js' {
  declare module.exports: $Exports<'swiper/cjs/utils/get-support'>;
}
declare module 'swiper/cjs/utils/utils.js' {
  declare module.exports: $Exports<'swiper/cjs/utils/utils'>;
}
declare module 'swiper/esm/components/a11y/a11y.js' {
  declare module.exports: $Exports<'swiper/esm/components/a11y/a11y'>;
}
declare module 'swiper/esm/components/autoplay/autoplay.js' {
  declare module.exports: $Exports<'swiper/esm/components/autoplay/autoplay'>;
}
declare module 'swiper/esm/components/controller/controller.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/controller/controller'
  >;
}
declare module 'swiper/esm/components/core/breakpoints/getBreakpoint.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/breakpoints/getBreakpoint'
  >;
}
declare module 'swiper/esm/components/core/breakpoints/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/breakpoints'>;
}
declare module 'swiper/esm/components/core/breakpoints/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/breakpoints'>;
}
declare module 'swiper/esm/components/core/breakpoints/setBreakpoint.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/breakpoints/setBreakpoint'
  >;
}
declare module 'swiper/esm/components/core/check-overflow/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/check-overflow'>;
}
declare module 'swiper/esm/components/core/check-overflow/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/check-overflow'>;
}
declare module 'swiper/esm/components/core/classes/addClasses.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/classes/addClasses'
  >;
}
declare module 'swiper/esm/components/core/classes/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/classes'>;
}
declare module 'swiper/esm/components/core/classes/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/classes'>;
}
declare module 'swiper/esm/components/core/classes/removeClasses.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/classes/removeClasses'
  >;
}
declare module 'swiper/esm/components/core/core-class.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/core-class'>;
}
declare module 'swiper/esm/components/core/defaults.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/defaults'>;
}
declare module 'swiper/esm/components/core/events-emitter.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/events-emitter'>;
}
declare module 'swiper/esm/components/core/events/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/events'>;
}
declare module 'swiper/esm/components/core/events/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/events'>;
}
declare module 'swiper/esm/components/core/events/onClick.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/events/onClick'>;
}
declare module 'swiper/esm/components/core/events/onResize.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/events/onResize'
  >;
}
declare module 'swiper/esm/components/core/events/onScroll.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/events/onScroll'
  >;
}
declare module 'swiper/esm/components/core/events/onTouchEnd.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/events/onTouchEnd'
  >;
}
declare module 'swiper/esm/components/core/events/onTouchMove.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/events/onTouchMove'
  >;
}
declare module 'swiper/esm/components/core/events/onTouchStart.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/events/onTouchStart'
  >;
}
declare module 'swiper/esm/components/core/grab-cursor/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/grab-cursor'>;
}
declare module 'swiper/esm/components/core/grab-cursor/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/grab-cursor'>;
}
declare module 'swiper/esm/components/core/grab-cursor/setGrabCursor.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/grab-cursor/setGrabCursor'
  >;
}
declare module 'swiper/esm/components/core/grab-cursor/unsetGrabCursor.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/grab-cursor/unsetGrabCursor'
  >;
}
declare module 'swiper/esm/components/core/images/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/images'>;
}
declare module 'swiper/esm/components/core/images/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/images'>;
}
declare module 'swiper/esm/components/core/images/loadImage.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/images/loadImage'
  >;
}
declare module 'swiper/esm/components/core/images/preloadImages.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/images/preloadImages'
  >;
}
declare module 'swiper/esm/components/core/loop/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/loop'>;
}
declare module 'swiper/esm/components/core/loop/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/loop'>;
}
declare module 'swiper/esm/components/core/loop/loopCreate.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/loop/loopCreate'
  >;
}
declare module 'swiper/esm/components/core/loop/loopDestroy.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/loop/loopDestroy'
  >;
}
declare module 'swiper/esm/components/core/loop/loopFix.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/loop/loopFix'>;
}
declare module 'swiper/esm/components/core/manipulation/addSlide.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/manipulation/addSlide'
  >;
}
declare module 'swiper/esm/components/core/manipulation/appendSlide.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/manipulation/appendSlide'
  >;
}
declare module 'swiper/esm/components/core/manipulation/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/manipulation'>;
}
declare module 'swiper/esm/components/core/manipulation/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/manipulation'>;
}
declare module 'swiper/esm/components/core/manipulation/prependSlide.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/manipulation/prependSlide'
  >;
}
declare module 'swiper/esm/components/core/manipulation/removeAllSlides.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/manipulation/removeAllSlides'
  >;
}
declare module 'swiper/esm/components/core/manipulation/removeSlide.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/manipulation/removeSlide'
  >;
}
declare module 'swiper/esm/components/core/modular.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/modular'>;
}
declare module 'swiper/esm/components/core/slide/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/slide'>;
}
declare module 'swiper/esm/components/core/slide/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/slide'>;
}
declare module 'swiper/esm/components/core/slide/slideNext.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/slide/slideNext'
  >;
}
declare module 'swiper/esm/components/core/slide/slidePrev.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/slide/slidePrev'
  >;
}
declare module 'swiper/esm/components/core/slide/slideReset.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/slide/slideReset'
  >;
}
declare module 'swiper/esm/components/core/slide/slideTo.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/slide/slideTo'>;
}
declare module 'swiper/esm/components/core/slide/slideToClickedSlide.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/slide/slideToClickedSlide'
  >;
}
declare module 'swiper/esm/components/core/slide/slideToClosest.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/slide/slideToClosest'
  >;
}
declare module 'swiper/esm/components/core/slide/slideToLoop.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/slide/slideToLoop'
  >;
}
declare module 'swiper/esm/components/core/transition/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/transition'>;
}
declare module 'swiper/esm/components/core/transition/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/transition'>;
}
declare module 'swiper/esm/components/core/transition/setTransition.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/transition/setTransition'
  >;
}
declare module 'swiper/esm/components/core/transition/transitionEnd.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/transition/transitionEnd'
  >;
}
declare module 'swiper/esm/components/core/transition/transitionStart.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/transition/transitionStart'
  >;
}
declare module 'swiper/esm/components/core/translate/getTranslate.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/translate/getTranslate'
  >;
}
declare module 'swiper/esm/components/core/translate/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/translate'>;
}
declare module 'swiper/esm/components/core/translate/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/translate'>;
}
declare module 'swiper/esm/components/core/translate/maxTranslate.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/translate/maxTranslate'
  >;
}
declare module 'swiper/esm/components/core/translate/minTranslate.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/translate/minTranslate'
  >;
}
declare module 'swiper/esm/components/core/translate/setTranslate.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/translate/setTranslate'
  >;
}
declare module 'swiper/esm/components/core/translate/translateTo.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/translate/translateTo'
  >;
}
declare module 'swiper/esm/components/core/update/index' {
  declare module.exports: $Exports<'swiper/esm/components/core/update'>;
}
declare module 'swiper/esm/components/core/update/index.js' {
  declare module.exports: $Exports<'swiper/esm/components/core/update'>;
}
declare module 'swiper/esm/components/core/update/updateActiveIndex.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/update/updateActiveIndex'
  >;
}
declare module 'swiper/esm/components/core/update/updateAutoHeight.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/update/updateAutoHeight'
  >;
}
declare module 'swiper/esm/components/core/update/updateClickedSlide.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/update/updateClickedSlide'
  >;
}
declare module 'swiper/esm/components/core/update/updateProgress.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/update/updateProgress'
  >;
}
declare module 'swiper/esm/components/core/update/updateSize.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/update/updateSize'
  >;
}
declare module 'swiper/esm/components/core/update/updateSlides.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/update/updateSlides'
  >;
}
declare module 'swiper/esm/components/core/update/updateSlidesClasses.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/update/updateSlidesClasses'
  >;
}
declare module 'swiper/esm/components/core/update/updateSlidesOffset.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/update/updateSlidesOffset'
  >;
}
declare module 'swiper/esm/components/core/update/updateSlidesProgress.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/core/update/updateSlidesProgress'
  >;
}
declare module 'swiper/esm/components/effect-coverflow/effect-coverflow.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/effect-coverflow/effect-coverflow'
  >;
}
declare module 'swiper/esm/components/effect-cube/effect-cube.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/effect-cube/effect-cube'
  >;
}
declare module 'swiper/esm/components/effect-fade/effect-fade.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/effect-fade/effect-fade'
  >;
}
declare module 'swiper/esm/components/effect-flip/effect-flip.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/effect-flip/effect-flip'
  >;
}
declare module 'swiper/esm/components/hash-navigation/hash-navigation.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/hash-navigation/hash-navigation'
  >;
}
declare module 'swiper/esm/components/history/history.js' {
  declare module.exports: $Exports<'swiper/esm/components/history/history'>;
}
declare module 'swiper/esm/components/keyboard/keyboard.js' {
  declare module.exports: $Exports<'swiper/esm/components/keyboard/keyboard'>;
}
declare module 'swiper/esm/components/lazy/lazy.js' {
  declare module.exports: $Exports<'swiper/esm/components/lazy/lazy'>;
}
declare module 'swiper/esm/components/mousewheel/mousewheel.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/mousewheel/mousewheel'
  >;
}
declare module 'swiper/esm/components/navigation/navigation.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/navigation/navigation'
  >;
}
declare module 'swiper/esm/components/pagination/pagination.js' {
  declare module.exports: $Exports<
    'swiper/esm/components/pagination/pagination'
  >;
}
declare module 'swiper/esm/components/parallax/parallax.js' {
  declare module.exports: $Exports<'swiper/esm/components/parallax/parallax'>;
}
declare module 'swiper/esm/components/scrollbar/scrollbar.js' {
  declare module.exports: $Exports<'swiper/esm/components/scrollbar/scrollbar'>;
}
declare module 'swiper/esm/components/thumbs/thumbs.js' {
  declare module.exports: $Exports<'swiper/esm/components/thumbs/thumbs'>;
}
declare module 'swiper/esm/components/virtual/virtual.js' {
  declare module.exports: $Exports<'swiper/esm/components/virtual/virtual'>;
}
declare module 'swiper/esm/components/zoom/zoom.js' {
  declare module.exports: $Exports<'swiper/esm/components/zoom/zoom'>;
}
declare module 'swiper/esm/modules/observer/observer.js' {
  declare module.exports: $Exports<'swiper/esm/modules/observer/observer'>;
}
declare module 'swiper/esm/modules/resize/resize.js' {
  declare module.exports: $Exports<'swiper/esm/modules/resize/resize'>;
}
declare module 'swiper/esm/react/get-changed-params.js' {
  declare module.exports: $Exports<'swiper/esm/react/get-changed-params'>;
}
declare module 'swiper/esm/react/get-children.js' {
  declare module.exports: $Exports<'swiper/esm/react/get-children'>;
}
declare module 'swiper/esm/react/get-params.js' {
  declare module.exports: $Exports<'swiper/esm/react/get-params'>;
}
declare module 'swiper/esm/react/init-swiper.js' {
  declare module.exports: $Exports<'swiper/esm/react/init-swiper'>;
}
declare module 'swiper/esm/react/loop.js' {
  declare module.exports: $Exports<'swiper/esm/react/loop'>;
}
declare module 'swiper/esm/react/params-list.js' {
  declare module.exports: $Exports<'swiper/esm/react/params-list'>;
}
declare module 'swiper/esm/react/swiper-slide.js' {
  declare module.exports: $Exports<'swiper/esm/react/swiper-slide'>;
}
declare module 'swiper/esm/react/swiper.js' {
  declare module.exports: $Exports<'swiper/esm/react/swiper'>;
}
declare module 'swiper/esm/react/update-swiper.js' {
  declare module.exports: $Exports<'swiper/esm/react/update-swiper'>;
}
declare module 'swiper/esm/react/use-isomorphic-layout-effect.js' {
  declare module.exports: $Exports<
    'swiper/esm/react/use-isomorphic-layout-effect'
  >;
}
declare module 'swiper/esm/react/utils.js' {
  declare module.exports: $Exports<'swiper/esm/react/utils'>;
}
declare module 'swiper/esm/react/virtual.js' {
  declare module.exports: $Exports<'swiper/esm/react/virtual'>;
}
declare module 'swiper/esm/utils/dom.js' {
  declare module.exports: $Exports<'swiper/esm/utils/dom'>;
}
declare module 'swiper/esm/utils/get-browser.js' {
  declare module.exports: $Exports<'swiper/esm/utils/get-browser'>;
}
declare module 'swiper/esm/utils/get-device.js' {
  declare module.exports: $Exports<'swiper/esm/utils/get-device'>;
}
declare module 'swiper/esm/utils/get-support.js' {
  declare module.exports: $Exports<'swiper/esm/utils/get-support'>;
}
declare module 'swiper/esm/utils/utils.js' {
  declare module.exports: $Exports<'swiper/esm/utils/utils'>;
}
declare module 'swiper/swiper-bundle.cjs.js' {
  declare module.exports: $Exports<'swiper/swiper-bundle.cjs'>;
}
declare module 'swiper/swiper-bundle.esm.browser.js' {
  declare module.exports: $Exports<'swiper/swiper-bundle.esm.browser'>;
}
declare module 'swiper/swiper-bundle.esm.browser.min.js' {
  declare module.exports: $Exports<'swiper/swiper-bundle.esm.browser.min'>;
}
declare module 'swiper/swiper-bundle.esm.js' {
  declare module.exports: $Exports<'swiper/swiper-bundle.esm'>;
}
declare module 'swiper/swiper-bundle.js' {
  declare module.exports: $Exports<'swiper/swiper-bundle'>;
}
declare module 'swiper/swiper-bundle.min.js' {
  declare module.exports: $Exports<'swiper/swiper-bundle.min'>;
}
declare module 'swiper/swiper-react.cjs.js' {
  declare module.exports: $Exports<'swiper/swiper-react.cjs'>;
}
declare module 'swiper/swiper-react.esm.js' {
  declare module.exports: $Exports<'swiper/swiper-react.esm'>;
}
declare module 'swiper/swiper.cjs.js' {
  declare module.exports: $Exports<'swiper/swiper.cjs'>;
}
declare module 'swiper/swiper.esm.js' {
  declare module.exports: $Exports<'swiper/swiper.esm'>;
}
