// flow-typed signature: ad5f50081372b4ea4c9dccdc74129fb8
// flow-typed version: <<STUB>>/swiper/react_v6.1.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swiper/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swiper/react' {
  declare module.exports: any;
}
